### ISSUE TITLE
If warped back to spawn via /back or tp, you are still considered in code in the arena

### ISSUE THREAD

**Issue by BootlegSanesss** [JohnCorby/GravityGuild#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JohnCorby** [comment]
this is intentional and wont be fixed as default players wont do /spawn
plus im working on it so i might not even have to store it besides on location so once you leave you'll not be "in the arena" anymore
