### ISSUE TITLE
if in arena /gg leave right before death you die at spawn after being stuck in elytra mode for like 2 secounds then a long respawn delay

### ISSUE THREAD

**Issue by BootlegSanesss** [JohnCorby/GravityGuild#7]

**Comment by JohnCorby** [comment]
the stuck in elytra mode is cuz the schematic is being pasted im pretty sure

**Comment by JohnCorby** [comment]
i could also probably fix it if i felt like it
ill also do it later

**Comment by JohnCorby** [comment]
# i cant fix the delay cuz thats just how schematics work but i did fix the death part

**Comment by BootlegSanesss** [comment]
coolo
